# Generated by Django 2.2.4 on 2019-09-03 09:56

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('pub_id', core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='public id')),
                ('content', models.CharField(max_length=100, verbose_name='content')),
                ('done', models.BooleanField(default=False, verbose_name='done')),
                ('todo_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.TodoUser')),
            ],
            options={
                'verbose_name': 'todo',
                'verbose_name_plural': 'todos',
            },
        ),
    ]
